Repository Ray-F/pyf-attendance, pull requests merged in 2021-02, with the labels that each got.

#2 Changed version number.
  client/src/containers/pages/HomePage.js
Labels: documentation

#3 Event list link
  client/src/components/event/EventList.js
Labels: enhancement

#13 Attendence Dashboard Dropdown Overhaul
  client/src/components/attendance/AttendanceForm.js
  server/controllers/EventController.js
  server/models/mongodb/MongoRepository.js
  server/routes/AttendanceRouter.js
Labels: feature, improvement
